### ISSUE TITLE
Trouble sing the code

### ISSUE THREAD

**Issue by Ana-Bastos** [zgabi/S63Tools#1]
Hi I would like to decrypt a s63 that i purchase colud you help me, i don't understand c# or the step that i need to do in order to decrypt s63 files.

**Comment by zgabi** [comment]
Hi,

Please download Visual Studio Community: https://visualstudio.microsoft.com/vs/community/
Install it.
Download the source code from this repository (clone or a zip, does not matter)
Double click on the S63Tools.sln file which will open VS.
You can start the application usually with F5.

That's very easy, you don't have to be a developer to do this.
I'm sorry, but I'm not a free service for cracking charts.

Let m know if you stuck somewhere in the installation... attach screenshot to this issue. I'll help you.
