### ISSUE TITLE
User Permit

### ISSUE THREAD

**Issue by JALLSL** [zgabi/S63Tools#2]
User Permit is a part of decrypting software as I understand from here: https://enterprise.arcgis.com/en/maritime/latest/chart-service/windows/managing-data-for-s-63-encrypted-datasets.htm

I've got a sample (bought it) of S-63 and I've got everything:
  - IHO certificate (IHO.CRT)
  - Cell permit (PERMIT.TXT)
  - Exchange set catalog file (CATALOG.031)

but no  User permit (USER_PERMIT.TXT).

I know this is not a free service, so you can charge us:)

**Comment by zgabi** [comment]
What did you buy exactly? An s-63 chart? From which site?

Yes, the user permit is generated on your device before you buy a chart. You should have one already. (However it is quite easy to generate a valid user permit, but it wont be comaptible with the encrypted chart you already boutht)
So what and how did you do?

**Comment by JALLSL** [comment]
We bought one S-63 chart, from official distributor, one of the leading ones. We payed a quote, than I've got a link to download. And there is everything structured like described in upper link, but there is no USER_PERMIT.TXT.
We actually got one file more: SERIAL.ENC

**Comment by zgabi** [comment]
If you have a cell permit (PERMIT.TXT), you shoud already have a user permit, because it contains your hardware id which is used for creating the cell permits. So if you not specify how you bought it exactly (on a website, from PC application, etc.), I can't help.

**Comment by JALLSL** [comment]
We have permit.txt as I mentioned. But we don't have any "user permit". We got a quote, paid it, then we get a link to primar website where we can see our data and download it.

**Comment by zgabi** [comment]
So you don't have any account on that website, just simply open a link, and you can download the files?
For example in o-charts.org you can find the user permit here:
![image](https://github.com/zgabi/S63Tools/assets/3104253/feb3e71e-1080-4e91-91e2-fd1d0a2b3256)

**Comment by zgabi** [comment]
Is it possible to share the files with me? At least 1 cell + the permit for that cell. If so, you can sent it to the following address zavarkog ... g m a i l .com

**Comment by JALLSL** [comment]
Thank you for updating the project! It works!
